### ISSUE TITLE
Unable to run cargo build

### ISSUE THREAD

**Issue by ashlinSajan** [Cargill/splinter#972] opened 2020-10-16 10:32 UTC
Getting this error while trying to run cargo build in the root directory 
Installed rustc nightly 1.49.0.still same issue
![IMG-20201016-WA0013](https://user-images.githubusercontent.com/34328137/96248183-cc46cd00-0fc8-11eb-94ad-54e0b70eeb1d.jpg)

**Comment by peterschwarz** [comment] 2020-10-16 16:47
Splinter currently only supports compilation against the stable rust compiler.

**Comment by ashlinSajan** [comment] 2020-10-19 03:52
> Splinter currently only supports compilation against the stable rust compiler.

So which version of rustc should I install?

**Comment by ashlinSajan** [comment] 2020-10-19 05:04
> Splinter currently only supports compilation against the stable rust compiler.

Will installing the stable version of rustc make the code work

**Comment by ashlinSajan** [comment] 2020-10-20 10:24
@peterschwarz please find the error log after installing stable version of rustc
![IMG-20201020-WA0056](https://user-images.githubusercontent.com/34328137/96573950-6fab2100-12ec-11eb-815c-5519b3d979c2.jpg)
![IMG-20201020-WA0058](https://user-images.githubusercontent.com/34328137/96573974-79348900-12ec-11eb-870d-c976d6dc24d0.jpg)

**Comment by ashlinSajan** [comment] 2020-10-20 10:24
![Uploading IMG-20201020-WA0058.jpg…]()

**Comment by ashlinSajan** [comment] 2020-10-20 10:27
![Uploading IMG-20201020-WA0057.jpg…]()

**Comment by leebradley** [comment] 2021-05-08 20:25
Hey @ashlinSajan, I know this is an older issue, but I just want to respond to provide some closure.

From your screenshots, this was your setup:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/indyuser/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.47 (18bf6b4f0 2020-10-07)
```

You were attempting to compile splinter main branch when you got the following error:

```
error[E0658]: non-builtin inner attributes are unstable
 --> /home/indyuser/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.18.0/src/well_known_types/struct_pb.rs:9:1
  |
  | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  | 
  = note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information
```

We can see from your screenshots that the source of your problem is rust complaining about protobuf 2.18.0 using the inner attribute `#![rustfmt::skip]`. What is confusing is that protobuf 2.18.0 supported Rust 1.47. In fact, they made a point to say the minimum supported version was 1.44.1 due to that specific custom inner attribute (see [changelog](https://github.com/stepancheg/rust-protobuf/blob/master/CHANGELOG.md#2150---2020-06-21)). And I'm not finding any information about a regression in either in Rust or protobuf.

I'm wondering if your version of rust was being correctly updated. If this was a more recent issue, I probably would have asked you if your `rustc --version` output matched the version displayed in `rustup show`.

Rust users encountered this and similar errors around that time for various projects, and the solution was to update rust and rebuild the project. See this [stackoverflow answer](https://stackoverflow.com/questions/63474498/errore0658-non-builtin-inner-attributes-are-unstable).

I suggest you run this:

```
rustup update stable
rustup show
rustc --version # Just to validate that the rustup did its job correctly, given your issue
cargo clean # Eliminate cache as a culprit
```

I think this issue is either a regression in rustc, a problem with rustup installing the correct version of rust on your system, or some kind of rust caching error.

In any case, if you update, clear the cache, and rebuild the main branch with the latest rust, this should no longer present a problem. Splinter targets support for latest stable Rust, and that's what we generally use for development.

**Comment by peterschwarz** [comment] 2021-08-09 18:53
Closing this, assuming the above comments have addressed the issue.  Please re-open if that is in error.

**Closed by peterschwarz** 2021-08-09 18:53 UTC
